#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

# Store the current directory to return later
original_dir=$(pwd)

# Create target directory if it doesn't exist and enter it
mkdir -p ~/code/build
cd ~/code/build

# Prerequisites installation (based on Ubuntu/Debian)
sudo apt update
sudo apt install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen

# Check if the Neovim repo already exists and clone or update it
if [ -d "neovim" ]; then
    echo "Neovim repository already exists. Fetching latest updates..."
    cd neovim
    git checkout stable
    git pull origin stable
else
    echo "Cloning Neovim repository..."
    git clone https://github.com/neovim/neovim.git
    cd neovim
    git checkout stable
fi

# Build
make CMAKE_BUILD_TYPE=RelWithDebInfo

# Build DEB package
cd build
cpack -G DEB

# Find the generated .deb package
deb_package=$(ls *.deb)

# Install the DEB package
sudo dpkg -i "$deb_package"

echo "Neovim has been installed successfully!"

# Return to the original directory
cd "$original_dir"

