#!/bin/bash

set -e

package_name="neovim"

find $HOME/.local/share/fonts -type f -name '*NerdFont*' -exec rm {} +

if dpkg -l | grep -qw "$package_name"; then
	echo "Uninstalling Neovim..."
	sudo dpkg --purge "$package_name"
	echo "Neovim has been uninstalled."
else
	echo "Neovim package is not installed."
fi

echo "Cleanup complete."
