- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
  - name: Update Cache
    apt:
      update_cache: true
    tags:
      - install
      - core
  tasks:
  - name: ssh
    import_tasks: tasks/ssh.yml
  - name: zsh
    import_tasks: tasks/zsh.yml
  - name: node
    import_tasks: tasks/node.yml
  - name: lazygit
    import_tasks: tasks/lazygit.yml
