- name: Installing stow
  apt: name=stow
  tags:
    - dotfiles
    - shell
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:knightSarai/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: yes
  tags:
    - dotfiles
    - shell
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && stow .
  tags:
    - dotfiles
    - shell
