- name: Backup existing .zshrc
  ansible.builtin.command:
    cmd: mv "/home/knight/.zshrc" "/home/knight/.zshrc.backup"
  args:
    creates: "/home/knight/.zshrc.backup"
  tags:
    - dotfiles
    - shell
- name: Installing stow
  apt: name=stow
  tags:
    - dotfiles
    - shell
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:knightSarai/.dotfiles.git'
    dest: "/home/knight/.dotfiles"
    accept_hostkey: yes
  tags:
    - dotfiles
    - shell
- name: Stow dotfiles
  shell: cd /home/knight/.dotfiles/ && stow .
  tags:
    - dotfiles
    - shell
