- name: Install Lazyvim packages
  apt:
    name:
      - curl
      - unzip
      - xclip
      - ripgrep
      - fd-find
      - fontconfig
    state: present
    update_cache: yes
  tags:
    - nvim

- name: Execute the build script for Neovim
  shell: "{{ playbook_dir }}/build-nvim"
  args:
    chdir: "{{ playbook_dir }}"
  become: yes
  become_user: root
  tags:
    - nvim
