- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
    owner: knight
    group: knight
  tags:
    - dotfiles
    - ssh
    - shell

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    owner: knight
    mode: 0600
  tags:
    - dotfiles
    - ssh
    - shell

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
    owner: knight
  tags:
    - dotfiles
    - ssh
    - shell

- name: Add public keys to authorized keys
  authorized_key:
    user: "knight"
    state: present
    key: "{{ lookup('file', item) }}"
  loop: "{{ lookup('fileglob', lookup('env', 'HOME') + '/.ssh/*.pub', wantlist=True) }}"
  tags:
    - dotfiles
    - ssh
    - shell
