- name: Install packages
  become: true
  apt:
    name: [ "tmux", "fzf",  "xclip", "ripgrep", "flameshot"]
  tags:
    - tools

- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  tags:
    - tools

- name: Copy tmux-sessionizer to ~/.local/bin
  ansible.builtin.copy:
    src: "{{playbook_dir}}/tmux-sessionizer"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/tmux-sessionizer"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  tags:
    - tools
